
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import net.sharkfw.kp.HubKP;
import net.sharkfw.peer.J2SESharkEngine;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SharkHubGUI.java
 *
 * Created on 17.10.2011, 14:48:46
 */
/**
 *
 * @author Jacob Zschunke
 */
public class SharkHubGUI extends javax.swing.JFrame {

    private final J2SESharkEngine se;
    private HubKP hubkp;
    
    /** Creates new form SharkHubGUI */
    public SharkHubGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.se = new J2SESharkEngine();
        System.setOut(new PrintStream(new OutputRedirecter()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        rbTCP = new javax.swing.JRadioButton();
        rbMAIL = new javax.swing.JRadioButton();
        tcpPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfPort = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spnTimeout = new javax.swing.JSpinner();
        mailPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfSMTP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfPOP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pwPassword = new javax.swing.JPasswordField();
        hubPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spnInterestCheck = new javax.swing.JSpinner();
        tfStatusPagePath = new javax.swing.JTextField();
        spnStatusPageUpdate = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnStatusPagePathChoose = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        spnInterestsValid = new javax.swing.JSpinner();
        buttonGroup1 = new javax.swing.ButtonGroup();
        statusPagePathChooser = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblStatusPage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jFrame1.setTitle("SharkHub - Setup");
        jFrame1.setMinimumSize(new java.awt.Dimension(672, 370));
        jFrame1.setName("jFrame1"); // NOI18N

        btnOK.setText("ok");
        btnOK.setName("btnOK"); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("cancel");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTCP);
        rbTCP.setText("TCP");
        rbTCP.setName("rbTCP"); // NOI18N
        rbTCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTCPActionPerformed(evt);
            }
        });
        rbTCP.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rbTCPPropertyChange(evt);
            }
        });

        buttonGroup1.add(rbMAIL);
        rbMAIL.setText("MAIL");
        rbMAIL.setName("rbMAIL"); // NOI18N
        rbMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMAILActionPerformed(evt);
            }
        });

        tcpPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tcpPanel.setName("tcpPanel"); // NOI18N

        jLabel3.setText("ConnectionTimeout");
        jLabel3.setName("jLabel3"); // NOI18N

        tfPort.setText("5555");
        tfPort.setToolTipText("specifies the Port the Hub will run on.");
        tfPort.setName("tfPort"); // NOI18N

        jLabel2.setText("Port");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setText("ms");
        jLabel4.setName("jLabel4"); // NOI18N

        spnTimeout.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(3000), Integer.valueOf(0), null, Integer.valueOf(100)));
        spnTimeout.setName("spnTimeout"); // NOI18N

        javax.swing.GroupLayout tcpPanelLayout = new javax.swing.GroupLayout(tcpPanel);
        tcpPanel.setLayout(tcpPanelLayout);
        tcpPanelLayout.setHorizontalGroup(
            tcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tcpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPort)
                    .addComponent(spnTimeout, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        tcpPanelLayout.setVerticalGroup(
            tcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tcpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mailPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mailPanel.setName("mailPanel"); // NOI18N

        jLabel5.setText("smtp");
        jLabel5.setName("jLabel5"); // NOI18N

        tfSMTP.setText("smtp.sharksystem.net");
        tfSMTP.setName("tfSMTP"); // NOI18N

        jLabel6.setText("pop");
        jLabel6.setName("jLabel6"); // NOI18N

        tfPOP.setText("pop.sharksystem.net");
        tfPOP.setName("tfPOP"); // NOI18N

        jLabel7.setText("user");
        jLabel7.setName("jLabel7"); // NOI18N

        tfUser.setName("tfUser"); // NOI18N

        jLabel8.setText("password");
        jLabel8.setName("jLabel8"); // NOI18N

        pwPassword.setName("pwPassword"); // NOI18N

        javax.swing.GroupLayout mailPanelLayout = new javax.swing.GroupLayout(mailPanel);
        mailPanel.setLayout(mailPanelLayout);
        mailPanelLayout.setHorizontalGroup(
            mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mailPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwPassword)
                    .addComponent(tfUser)
                    .addComponent(tfPOP)
                    .addComponent(tfSMTP, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addContainerGap())
        );
        mailPanelLayout.setVerticalGroup(
            mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfSMTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfPOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pwPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hubPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        hubPanel.setName("hubPanel"); // NOI18N

        jLabel9.setText("Interests Validtime");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText("Interest Check");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText("Path to Statuspage");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText("Statuspage Update");
        jLabel12.setName("jLabel12"); // NOI18N

        spnInterestCheck.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1000), Integer.valueOf(0), null, Integer.valueOf(100)));
        spnInterestCheck.setName("spnInterestCheck"); // NOI18N
        spnInterestCheck.setValue(1000);

        tfStatusPagePath.setText("status.html");
        tfStatusPagePath.setName("tfStatusPagePath"); // NOI18N

        spnStatusPageUpdate.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10000), Integer.valueOf(0), null, Integer.valueOf(100)));
        spnStatusPageUpdate.setName("spnStatusPageUpdate"); // NOI18N
        spnStatusPageUpdate.setValue(10000);

        jLabel13.setText("ms");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText("ms");
        jLabel14.setName("jLabel14"); // NOI18N

        btnStatusPagePathChoose.setText("...");
        btnStatusPagePathChoose.setName("btnStatusPagePathChoose"); // NOI18N
        btnStatusPagePathChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusPagePathChooseActionPerformed(evt);
            }
        });

        jLabel15.setText("ms");
        jLabel15.setName("jLabel15"); // NOI18N

        spnInterestsValid.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(300000L), Long.valueOf(0L), null, Long.valueOf(100L)));
        spnInterestsValid.setName("spnInterestsValid"); // NOI18N

        javax.swing.GroupLayout hubPanelLayout = new javax.swing.GroupLayout(hubPanel);
        hubPanel.setLayout(hubPanelLayout);
        hubPanelLayout.setHorizontalGroup(
            hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hubPanelLayout.createSequentialGroup()
                        .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hubPanelLayout.createSequentialGroup()
                                .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(16, 16, 16)
                                .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spnInterestsValid, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(spnInterestCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)))
                            .addComponent(jLabel11))
                        .addContainerGap())
                    .addGroup(hubPanelLayout.createSequentialGroup()
                        .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, hubPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnStatusPageUpdate))
                            .addComponent(tfStatusPagePath, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hubPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStatusPagePathChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hubPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel15)
                                .addContainerGap())))))
        );
        hubPanelLayout.setVerticalGroup(
            hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(spnInterestsValid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spnInterestCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStatusPagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatusPagePathChoose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spnStatusPageUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTCP)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMAIL)
                            .addComponent(mailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tcpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbTCP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addComponent(hubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOK)
                            .addComponent(btnCancel)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(tcpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMAIL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusPagePathChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        statusPagePathChooser.setName("statusPagePathChooser"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SharkHub");
        setIconImages(null);

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        lblStatusPage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblStatusPage.setName("lblStatusPage"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStatusPage, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStatusPage, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Status", jPanel1);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        taOutput.setColumns(20);
        taOutput.setEditable(false);
        taOutput.setRows(5);
        taOutput.setAutoscrolls(true);
        taOutput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        taOutput.setName("taOutput"); // NOI18N
        jScrollPane1.setViewportView(taOutput);

        jTabbedPane1.addTab("Output", jScrollPane1);

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setText("coming soon");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel1)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(233, 233, 233))
        );

        jTabbedPane1.addTab("Info", jPanel2);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("File");
        jMenu1.setName("jMenu1"); // NOI18N

        jMenuItem1.setText("start Hub");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setText("stop Hub");
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("exit");
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("?");
        jMenu3.setName("jMenu3"); // NOI18N

        jMenuItem4.setText("Help");
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenu3.add(jMenuItem4);

        jMenuItem2.setText("About");
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Output");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.jFrame1.setVisible(true);
        this.jFrame1.setEnabled(true);
        this.jFrame1.setLocationRelativeTo(this);
                
        this.rbTCP.setSelected(true);

        tcpPanel.setEnabled(true);
        Component[] comps = tcpPanel.getComponents();
        for (Component c : comps) {
            c.setEnabled(true);
        }

        mailPanel.setEnabled(false);
        comps = mailPanel.getComponents();
        for (Component c : comps) {
            c.setEnabled(false);
        }
        
        this.clearForm();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void clearForm() {
        rbTCP.setSelected(true);
        rbMAIL.setSelected(false);
        
        tfPort.setText("5555");
        spnTimeout.setValue(3000);
        
        tfSMTP.setText("smtp.sharksystem.net");
        tfPOP.setText("pop.sharksystem.net");
        tfUser.setText("");
        pwPassword.setText("");
        
        spnInterestsValid.setValue((long) 300000);
        spnInterestCheck.setValue(1000);
        tfStatusPagePath.setText("status.html");
        spnStatusPageUpdate.setValue(10000);
    }
    
    private void rbTCPPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rbTCPPropertyChange
    }//GEN-LAST:event_rbTCPPropertyChange

    private void rbTCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTCPActionPerformed
        tcpPanel.setEnabled(true);
        Component[] comps = tcpPanel.getComponents();
        for (Component c : comps) {
            c.setEnabled(true);
        }

        mailPanel.setEnabled(false);
        comps = mailPanel.getComponents();
        for (Component c : comps) {
            c.setEnabled(false);
        }
    }//GEN-LAST:event_rbTCPActionPerformed

    private void rbMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMAILActionPerformed
        tcpPanel.setEnabled(false);
        Component[] comps = tcpPanel.getComponents();
        for (Component c : comps) {
            c.setEnabled(false);
        }

        mailPanel.setEnabled(true);
        comps = mailPanel.getComponents();
        for (Component c : comps) {
            c.setEnabled(true);
        }
    }//GEN-LAST:event_rbMAILActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.jFrame1.setVisible(false);        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        long interestsValid = (Long) spnInterestsValid.getValue();
        int interestCheck = (Integer) spnInterestCheck.getValue();
        String statuspagePath = tfStatusPagePath.getText();
        int statusUpdate = (Integer) spnStatusPageUpdate.getValue();
        
        this.hubkp = new HubKP(se, interestsValid, interestCheck, statuspagePath, statusUpdate);
        this.hubkp.setAdditionalOutput(new StatusPageOutputStream());        
        
        if(statuspagePath == null || statuspagePath.equalsIgnoreCase("")) {
            hubkp = null;
            return;
        }
        
        if(rbTCP.isSelected()) {
            String sPort = tfPort.getText();
            int port = 5555;
            if(sPort != null && !sPort.equalsIgnoreCase("")) {
                try {
                    port = Integer.parseInt(sPort);
                } catch(NumberFormatException nfe) {
                    hubkp = null;
                    return;
                }
            }
            int timeout = (Integer) spnTimeout.getValue();
            
            se.startTCP(port);
            se.setConnectionTimeOut(timeout);
        } else if(rbMAIL.isSelected()) {
            String smtp = tfSMTP.getText();
            String pop = tfPOP.getText();
            String user = tfUser.getText();
            String pw = pwPassword.getText();
            
            if(!validateText(smtp) || !validateText(pop) || !validateText(user) || !validateText(pw)) {
                hubkp = null;
                return;
            }
            
            se.setMailConfiguration(smtp, user, pw, pop, user, user, pw, 1);
            se.startMail();
        }
        
        this.jFrame1.setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private boolean validateText(String s) {
        if(s == null || s.equalsIgnoreCase("")) {
            return false;
        }
        return true;
    }
    
    private void btnStatusPagePathChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusPagePathChooseActionPerformed
        this.statusPagePathChooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.getName().endsWith(".html") || f.getName().endsWith(".htm")) {
                    return true;
                }
                return false;
            }

            @Override
            public String getDescription() {
                return "Only .html and .htm Files will be accepted!";
            }
        });
        
        int result = this.statusPagePathChooser.showSaveDialog(hubPanel);
        if(result == JFileChooser.APPROVE_OPTION) {
            File f = statusPagePathChooser.getSelectedFile();
            this.tfStatusPagePath.setText(f.getPath());
        }
        
    }//GEN-LAST:event_btnStatusPagePathChooseActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        se.deleteKP(hubkp);
        hubkp = null;
        se.stop();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SharkHubGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(SharkHubGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(SharkHubGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(SharkHubGUI.class.getName()).log(Level.SEVERE, null, ex);
        }      
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SharkHubGUI().setVisible(true);
            }
        });

    }
    
    private class StatusPageOutputStream extends OutputStream {               
        @Override
        public void write(int b) throws IOException {/* do nothing */}

        @Override
        public void write(byte[] b) throws IOException {
            lblStatusPage.setText(new String(b));
        }                
    }
    
    private class OutputRedirecter extends OutputStream {        
        @Override
        public void write(byte[] b) throws IOException {
            taOutput.append(new String(b));
        }

        @Override
        public void write(int b) throws IOException {
            taOutput.append(String.valueOf((char) b));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnStatusPagePathChoose;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel hubPanel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblStatusPage;
    private javax.swing.JPanel mailPanel;
    private javax.swing.JPasswordField pwPassword;
    private javax.swing.JRadioButton rbMAIL;
    private javax.swing.JRadioButton rbTCP;
    private javax.swing.JSpinner spnInterestCheck;
    private javax.swing.JSpinner spnInterestsValid;
    private javax.swing.JSpinner spnStatusPageUpdate;
    private javax.swing.JSpinner spnTimeout;
    private javax.swing.JFileChooser statusPagePathChooser;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JPanel tcpPanel;
    private javax.swing.JTextField tfPOP;
    private javax.swing.JTextField tfPort;
    private javax.swing.JTextField tfSMTP;
    private javax.swing.JTextField tfStatusPagePath;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
